# Data buku-buku
buku = [
    {"judul": "Harry Potter and the Sorcerer's Stone", "penulis": "J.K. Rowling", "genre": "Fantasi"},
    {"judul": "To Kill a Mockingbird", "penulis": "Harper Lee", "genre": "Fiksi"},
    {"judul": "1984", "penulis": "George Orwell", "genre": "Dystopia"},
    {"judul": "The Great Gatsby", "penulis": "F. Scott Fitzgerald", "genre": "Fiksi"},
    {"judul": "Pride and Prejudice", "penulis": "Jane Austen", "genre": "Romansa"},
    {"judul": "The Hobbit", "penulis": "J.R.R. Tolkien", "genre": "Fantasi"},
    {"judul": "Animal Farm", "penulis": "George Orwell", "genre": "Satire"},
    {"judul": "Supernova", "penulis": "Dee Lestari", "genre": "Fiksi Sains"},
    {"judul": "Cantik Itu Luka", "penulis": "Eka Kurniawan", "genre": "Fiksi"},
    {"judul": "The Subtle Art of Not Giving a Fuck", "penulis": "Mark Manson", "genre": "Pengembangan Diri"},
    {"judul": "Black Showman dan Pembunuh di Kota Tak Bernama", "penulis": "Keigo Higashino", "genre": "Misteri"},
    {"judul": "The Silent Patient", "penulis": "Alex Michaelides", "genre": "Thriller"},
    {"judul": "Alchemised", "penulis": "SenLinYu", "genre": "Dark fantasy"},
    {"judul": "Daisy Jones & The Six", "penulis": "Taylor Jenkins Reid", "genre": "Fiksi musik, drama"},
    {"judul": "Onyx Storm", "penulis": "Rebecca Yarros", "genre": "Fantasy romantis"},
    {"judul": "The Midnight Library", "penulis": "Matt Haig", "genre": "Fiksi filosofis"},
    {"judul": "The Song of Achilles", "penulis": "Madeline Miller", "genre": "Mitologi, Romance"},
    {"judul": "It Ends With Us", "penulis": "Colleen Hoover", "genre": "Romansa"},
    {"judul": "The Psychology of Money", "penulis": "Morgan Housel", "genre": "Keuangan, Nonfiksi"},
    {"judul": "The Hunger Games", "penulis": "Suzanne Collins", "genre": "Dystopia"},
    {"judul": "Percy Jackson & The Olympians", "penulis": "Rick Riordan", "genre": "Fantasi"},
    {"judul": "Norwegian Wood", "penulis": "Haruki Murakami", "genre": "Drama, Romance"},
    {"judul": "Kita Pergi Hari Ini", "penulis": "Ziggy Zezsyazeoviennazabrizkie", "genre": "Fiksi"},
    {"judul": "Laut Bercerita", "penulis": "Leila S. Chudori", "genre": "Fiksi historis"},
    {"judul": "The Girl on the Train", "penulis": "Paula Hawkins", "genre": "Thriller"},
    {"judul": "One Piece: East Blue", "penulis": "Eiichiro Oda", "genre": "Petualangan"},
    {"judul": "Think Again", "penulis": "Adam Grant", "genre": "Psikologi"},
    {"judul": "Sapiens", "penulis": "Yuval Noah Harari", "genre": "Sejarah, Nonfiksi"},
    {"judul": "Atomic Habits", "penulis": "James Clear", "genre": "Pengembangan diri"},
    {"judul": "The Name of the Wind", "penulis": "Patrick Rothfuss", "genre": "Fantasi"},
    {"judul": "The Maze Runner", "penulis": "James Dashner", "genre": "Dystopia"},
    {"judul": "Ready Player One", "penulis": "Ernest Cline", "genre": "Fiksi Sains"},
    {"judul": "The Fault in Our Stars", "penulis": "John Green", "genre": "Romansa, Drama"},
    {"judul": "Before the Coffee Gets Cold", "penulis": "Toshikazu Kawaguchi", "genre": "Fiksi, Drama"},
    {"judul": "Educated", "penulis": "Tara Westover", "genre": "Memoar"},
    {"judul": "Becoming", "penulis": "Michelle Obama", "genre": "Memoar"},
    {"judul": "Where the Crawdads Sing", "penulis": "Delia Owens", "genre": "Misteri, Drama"},
    {"judul": "The Alchemist", "penulis": "Paulo Coelho", "genre": "Filosofi, Petualangan"},
    {"judul": "Good Omens", "penulis": "Terry Pratchett & Neil Gaiman", "genre": "Fantasi, Komedi"},
    {"judul": "The Seven Husbands of Evelyn Hugo", "penulis": "Taylor Jenkins Reid", "genre": "Drama"},
    {"judul": "The Martian", "penulis": "Andy Weir", "genre": "Sci-Fi"},
    {"judul": "Gone Girl", "penulis": "Gillian Flynn", "genre": "Thriller psikologis"},
    {"judul": "Filosofi Teras", "penulis": "Henry Manampiring", "genre": "Filsafat, Self-help"},
    {"judul": "The Art of War", "penulis": "Sun Tzu", "genre": "Strategi"},
    {"judul": "The Power of Habit", "penulis": "Charles Duhigg", "genre": "Psikologi, Self-help"}
]
